name: Frontend CI/CD

on:
  push:
    paths: "FE/**"
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: make .env.local
        run: |
          cd ./FE
          touch ./.env.local
          echo "${{ secrets.ENV }}" > ./.env.local
      - name: Install Dependencies
        run: cd ./FE && npm install

      - name: Build
        run: cd ./FE && npm run build

      - uses: awact/s3-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: "./FE/out"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
